// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbTByPejzNq4FBsZuoGnj6Uqop3MNjjQ',
    appId: '1:358925655292:web:4a08b5362c84456a090b79',
    messagingSenderId: '358925655292',
    projectId: 'qg-fastfood-11f43',
    authDomain: 'qg-fastfood-11f43.firebaseapp.com',
    storageBucket: 'qg-fastfood-11f43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gmk4DQfsbAl9JC8XwxY_ood8noO4crs',
    appId: '1:358925655292:android:369c515d40187045090b79',
    messagingSenderId: '358925655292',
    projectId: 'qg-fastfood-11f43',
    storageBucket: 'qg-fastfood-11f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL24tgnrwrKFl5IbAeDhKtT8eGkhfpS24',
    appId: '1:358925655292:ios:0f55366c4f2d964e090b79',
    messagingSenderId: '358925655292',
    projectId: 'qg-fastfood-11f43',
    storageBucket: 'qg-fastfood-11f43.firebasestorage.app',
    iosBundleId: 'com.example.qgFastfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL24tgnrwrKFl5IbAeDhKtT8eGkhfpS24',
    appId: '1:358925655292:ios:0f55366c4f2d964e090b79',
    messagingSenderId: '358925655292',
    projectId: 'qg-fastfood-11f43',
    storageBucket: 'qg-fastfood-11f43.firebasestorage.app',
    iosBundleId: 'com.example.qgFastfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZbTByPejzNq4FBsZuoGnj6Uqop3MNjjQ',
    appId: '1:358925655292:web:4dc518a400a368f5090b79',
    messagingSenderId: '358925655292',
    projectId: 'qg-fastfood-11f43',
    authDomain: 'qg-fastfood-11f43.firebaseapp.com',
    storageBucket: 'qg-fastfood-11f43.firebasestorage.app',
  );
}
